### ISSUE TITLE
Results history is not generated

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/ui-profiler#28]
## Description

Results history is not generated in UI, or in `<root-dir>/ui-profiler-results`.

## Reproduce

1. I run one instance of profiling - style sheets + switch tabs with number of repeats set to 5
2. After it is done, I can examine the results in the lower half of the screen as mentioned in the User guide
3. I can also see a corresponding `profile.json` file in `<root-dir>/ui-profiler-results`
4. I now run a second instance of profiling - style sheets + switch tabs with number of repeats set to 10. I did not change any configuration option other than number of repeats for this iteration
5. After it is complete, I can see the results again in the lower half of the screen, however, I dont see an entry for the previous run anymore
6. I dont see a second profile.json file in `<root-dir>/ui-profiler-results` either.

This is the screen after the second iteration. Note the file browser on the left is open to the `<root-dir>/ui-profiler-results` dir and has only one entry.

![image](https://user-images.githubusercontent.com/19615498/213918998-962a92f6-1b49-4d4b-abe2-1b57bb54e792.png)

## Expected behavior

A list of entries in result history each corresponding to an iteration.

Please point out if this is a case of incorrect usage.

## Context

- JupyterLab version: 3.5.2

**Comment by suganya-sk** [comment]
Another case where the two consecutive iterations are different benchmarks themselves - 

I ran a execution time + switch menu iteration, after the two iterations of style-sheet + tab switch in Update#1 ; the results were generated as expected. However, the results history does not have an entry for this iteration and remains in the very first result; the `ui-profiler-results` dir on the file browser also does not have a new entry for the last iteration.

![image](https://user-images.githubusercontent.com/19615498/213919851-bf8c6e36-2fd4-4861-980b-366b569aeca7.png)

**Comment by krassowski** [comment]
This is a bug with report upload happening when the current directory != root directory.
