### ISSUE TITLE
Error 'file or directory does not exist: 'ui-profiler-results' while benchmarking Execution time

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/ui-profiler#36]
## Description

While benchmarking Execution time, the tests run successfully but the results are not stored as expected. I get the error '- file or directory does not exist: 'ui-profiler-results' - and the results directory is not created at all.

## Reproduce

1. Select benchmark - Execution Time
2. Select scenario - Open Menu
3. Click start
4. The benchmark test runs through without any issues; the box plot is displayed as expected
5. However, there are no .profile.json result files on the left
6. Terminal has the following error - file or directory does not exist: 'ui-profiler-results' 

## Expected behavior

The folder ui-profiler-results is created as needed

## Context

- Browser and version: Chrome 110
- JupyterLab version: 3.6.1
- ui-profiler-version: 0.1.6

**Comment by suganya-sk** [comment]
Here is a screenshot of the error in terminal with more details - 

![image](https://user-images.githubusercontent.com/19615498/223432936-825fdd29-d5e6-4a68-8d90-b5ddf422abe2.png)

**Comment by krassowski** [comment]
The results directory should be created by this call:

https://github.com/jupyterlab/ui-profiler/blob/b351f8f0edd5da9281b398e660efd4bbe3f8c5e1/src/ui.tsx#L615-L617

however if user deletes the directory after it will be created they will see an error as above. If you did not delete the directory in the meantime that would be an interesting bug and it would be helpful to see the server long on the initial `save` that was supposed to create the directory.

**Comment by suganya-sk** [comment]
Interestingly, I had the issue occur in both scenarios - the files were not created in the existing `ui-profiler-results` folder. So, I deleted the existing folder to see if a new folder would be created and still had the issue.

The screenshot I shared previously was taken after deleting the folder.
